<?php
$categories = Mage::getModel('catalog/category')->getCollection()
    ->addAttributeToSelect('*')
    ->setOrder('thumbnail_home', 'ASC');//or you can just add some attributes
   // ->addAttributeToFilter('level', 2)//2 is actually the first level
    //->addAttributeToFilter('is_active', 1)//if you want only active categories
;
?>
<div class="page-title category-title center">
            <h1>Our Women's Fashion Collection</h1>
    </div>
<div class="clear"></div>
<ul class="row-cat grid-clol-6">
<?php foreach($categories as $category): ?>
<?php //echo $category->getThumbnailHome() ?>
<?php if($category->getShowCatimage()==1): ?>
	<li class="col-item3">

	<a href="<?php echo $category->getCategoryIdUrl(); ?>">
			<img  src="<?php echo $category->getThumbnailImageUrl(); ?>"/>
			<div class="content-center">
				<div class="row-title"><?php echo $category->getName(); ?></div>
				<div class="row-button"><button class ="row-inner" >Shop</button></div>
			</div>
		</a>
	</li>
<?php endif; ?>
<?php endforeach;?>
</ul>
