<?php
//$_productCollection=$this->getLoadedProductCollection();
//$_helper = $this->helper('catalog/output');
?>
       

<?php
$todayDate = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

$_productCollection = $this->getLoadedProductCollection();
$_productCollection = Mage::getResourceModel('catalog/product_collection')
        ->addAttributeToSelect('*')
        ->addAttributeToFilter('news_from_date', array('date' => true, 'to' => $todayDate))
        ->addAttributeToFilter('news_to_date', array('or' => array(
                0 => array('date' => true, 'from' => $todayDate),
                1 => array('is' => new Zend_Db_Expr('null')))
                ), 'left')
        ->addFieldToFilter('visibility', Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH);
;

$now = date("Y-m-d");
$newsFrom = substr($_productCollection->getData('news_from_date'), 0, 10);
$newsTo = substr($_productCollection->getData('news_to_date'), 0, 10);
//echo $_productCollection->count();
?>
<?php if (($_products = $_productCollection) && $_products->getSize()): ?>
   
    <div class="widget widget-catalogsale-products <?php echo $_homeIndent; ?>">
        <div class="page-title category-title center">
           <!-- <h1><?php echo $this->__('Latest Indian Kurtis, Cotton Dresses & more.') ?></h1>  -->
            <h1><?php echo $this->__('NEW ARRIVALS') ?></h1>

        </div> 
		<div class="owl-carousel owl-theme">
            <?php $suffix = $this->getNameInLayout(); ?>
		
				<?php foreach ($_products->getItems() as $_product): ?>
                <div class="item <?php echo $_itemwidth; ?>">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250, 383) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
						</a>
                        <div class="product-shop">
                            <?php
                            $productObject = Mage::getModel('catalog/product')->load($_product->getId());
                            ?>
                            <h3 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                    <?php
                                    $small_getName = strip_tags($this->htmlEscape($_product->getName()));
                                    if (strlen($small_getName) < 20)
                                        echo($small_getName);
                                    else {
                                        echo mb_substr($small_getName, 0, 20, 'UTF-8') . '...';
                                    }
                                    ?>
                                </a>
                            </h3>
                            <?php echo $this->getPriceHtml($productObject, true); ?>
                        </div>
					<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
							<div class="label-product">             
								<?php if ($_product->getData('new')) {
									echo '<span class="new">' . $this->__('New') . '</span>';
								} ?>
								<?php if ($_product->getData('sale')) {
									echo '<span class="sale">' . $this->__('Sale') . '</span>';
								} ?>
                        </div>
                </div>
				<?php endforeach; ?>
</div>

        
    <?php echo "$_slidControl2"; ?>
        <script type="text/javascript">decorateList('widget-catalogsale-products-<?php echo $suffix; ?>', 'none-recursive')</script>
    </div>
<?php endif; ?>
<?php /* if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' ) :  ?>
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block-row-1')->toHtml() ?>
  <?php endif; */ ?>
