<div class="home-id homeIndent">
    <div class="page-title category-title center">
        <h1>Customer Reviews</h1>
    </div>
    <div class="caroufredsel_wrapper" style="display: block; text-align: left; float: none; position: relative; top: 0px; right: 0px; bottom: 0px; left: 0px; z-index: auto; width: 1158px; height: 431px; margin: 0px; overflow: hidden;">
        <ul class="products-grid new_triger homeSider first last odd" style="text-align: left; float: none; position: absolute; top: 0px; right: auto; bottom: auto; left: 0px; margin: 0px; width: 8106px; height: 431px; z-index: auto;">



            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>>
                <div class="wrapper-hover">
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    <div class="clear"></div>
                </div>
            </li>
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li>
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                   Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li>
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li> 
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li>  
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li> 
            <li itemtype="http://schema.org/product" itemscope="" class="item free " style="width: 193px;">
				<h3>Rewview By : Customer 1</h3>
                <div class="wrapper-hover">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </div>
            </li>  
        </ul>
    </div>
    <div class="home-carousel-control">
        <a href="#" class="carousel-prev fa fa-chevron-left" style="display: block;"></a>
        <a href="#" class="carousel-next fa fa-chevron-right" style="display: block;"></a>
    </div>
    <script type="text/javascript">
        decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])
    </script>
</div>
