<?php 
?>

<?php
$height = Mage::getStoreConfig('facebooklb/general/height');
$width   = Mage::getStoreConfig('facebooklb/general/width');
$username  = Mage::getStoreConfig('facebooklb/general/username');
if($username == '')
{
	$username = 'SoftProdigy';
}
?>
<div class="block">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=249628161746894";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like-box" data-href="http://www.facebook.com/<?=$username?>" data-width="<?=$width?>" data-height="<?=$height?>" data-show-faces="true" data-stream="false" data-header="true"></div>
</div>
