<?php
?>

<?php
$widgetid  = Mage::getStoreConfig('twitterlb/general/widgetid');
$username  = Mage::getStoreConfig('twitterlb/general/username');
if($username == '')
{
	$username = 'softprodigy';
}
?>
<div class="block">
	<a class="twitter-timeline"  href="https://twitter.com/softprodigy"  data-widget-id="<?php echo $widgetid; ?>">Tweets by @<?php echo $username; ?></a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
