<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/klass.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/code.photoswipe.jquery-3.0.5.js') ?>"></script>
<?php
/**
 * Cloud Image Zoom - Magento Extension
 *
 * @package     CloudZoom
 * @category    EcommerceTeam
 * @copyright   Copyright 2011 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    1.1.3
 */

/** @var $this Mage_Catalog_Block_Product_View_Media */
/** @var $product Mage_Catalog_Model_Product */
$product      = $this->getProduct();
/** @var $helper EcommerceTeam_CloudZoom_Helper_Data */
$helper       = Mage::helper('ecommerceteam_cloudzoom');
/** @var $outputHelper Mage_Core_Block_Abstract */
$outputHelper = $this->helper('catalog/output');

$position       = $helper->getConfigData('position');
$showTitle      = intval($helper->getConfigFlag('show_title'));
$titleOpacity   = intval($helper->getConfigData('title_opacity')) / 100;
$lensOpacity    = intval($helper->getConfigData('lens_opacity')) / 100;
$tintColor      = trim($helper->getConfigData('tint_color'));
$tintOpacity    = intval($helper->getConfigData('tint_opacity')) / 100;
$zoomWidth      = intval($helper->getConfigData('zoom_width'));
$zoomHeight     = intval($helper->getConfigData('zoom_height'));
$bigImageWidth  = intval($helper->getConfigData('big_image_width'));
$bigImageHeight = intval($helper->getConfigData('big_image_height'));

$bigImageX  = 384;
$bigImageY = 450;

$config = array(
    "position:'{$position}'",
    "showTitle:{$showTitle}",
    "titleOpacity:{$titleOpacity}",
    "lensOpacity:{$lensOpacity}",
);
    
if ($position == 'inside') {
    $config[] = 'adjustX: -4,adjustY:-4';
} elseif ($position == 'right') {
    $config[] = 'adjustX: 10,adjustY:-4';
} elseif ($position == 'bottom') {
    $config[] = 'adjustX: -4,adjustY:10';
} elseif ($position == 'left') {
    $config[] = 'adjustX: -18,adjustY:-4';
} elseif ($position == 'top') {
    $config[] = 'adjustX: -4,adjustY:-18';
}

if ($tintColor) {
    $config[] = "tint:'{$tintColor}',tintOpacity:{$tintOpacity}";
}

if ($zoomWidth) {
    $config[] = "zoomWidth:{$zoomWidth}";
}

if ($zoomHeight) {
    $config[] = "zoomHeight:{$zoomHeight}";
}
?>
			
<?php if ($zoomWidth > 50 and $zoomHeight > 50  ): ?>
<style type="text/css">
.cloud-zoom-big {width:<?php echo "$zoomWidth"; ?>px !important; height:<?php echo "$zoomHeight"; ?>px !important;  }
div.mousetrap{ cursor:url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'zoom_icon.png' ?>), auto !important; }
</style>
<?php endif; ?>

 <div class="more-views desktop">
        <h2><?php echo $this->__('More Views') ?></h2>
        <div class="container-slider">
            <ul class="slider <?php echo $carous;?>" >
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <li>
                    <a href='<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>' class='cloud-zoom-gallery' title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'
                    rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageX, $bigImageY);?>' ">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(97,149);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
            <?php echo "$tumbSliderControl"; ?>
        </div>
    </div>

<div class="product-box-customs">
    <?php if ($product->getImage() != 'no_selection' && $product->getImage()): ?>
    
    <p class="product-image">
        <a  href='<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($bigImageWidth, $bigImageHeight);?>' class = 'cloud-zoom' id='zoom1' rel="<?php echo implode($config, ',');?>">
            
            <img class="big" id="image" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($bigImageX, $bigImageY);?>" alt='' title="<?php echo $this->htmlEscape($this->getImageLabel());?>" />
             <i class="fa fa-search-plus" aria-hidden="true"></i>
        </a>
    </p>
    <?php else: ?>
    <p class="product-image">
        <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($product, 'image')->resize($bigImageX, $bigImageY).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
        ?>
    </p>

    <?php endif; ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
    
         <?php if (count($this->getGalleryImages()) > 6)  {
            $carous='tumbSlider';
            $tumbSliderControl = '<a class="tumbSlider-prev fa fa-chevron-circle-left" href="#"></a>
            <a class="tumbSlider-next fa fa-chevron-circle-right" href="#"></a>';
        } else 
            {  
                $tumbSliderControl ='';
                $carous='tumbSlider-none';
            } ?>
    
   
    
    
    <!----Our added code----->

	 <script type="text/javascript" charset="utf-8">	
			jQuery(document).on("click",".mousetrap", function(){									
					 setTimeout(function() {
						jQuery("ul.gallery li:first-child a").trigger('click');
					},10);								
			});
			
			
			jQuery(document).ready(function(){							
			
					jQuery("area[rel^='prettyPhoto']").prettyPhoto();					
					jQuery(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',theme:'light_square',slideshow:3000, autoplay_slideshow: false});
					jQuery(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'slow',slideshow:10000, hideflash: true});
			
					jQuery("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
						custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
						changepicturecallback: function(){ initialize(); }
					});

					jQuery("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
						custom_markup: '<div id="bsap_1259344" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div><div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
						changepicturecallback: function(){ _bsap.exec(); }
					});
				
			});					
			</script>
			
			<!---- Div for slider of light box slide show ------>
		
				 <ul class="gallery">
				<?php foreach ($this->getGalleryImages() as $_image): ?>            
						   <li><a href='<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>' rel='prettyPhoto[gallery2]'></a> </li>          
						<?php endforeach; ?>    
				</ul>        
			<!---- Div end here for light box slide show -------->		
				

	<!----End Our added code----->	
        
        <div class="gallery-swipe-content">
            <ul id="gallery-swipe" class="gallery-swipe">
                <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <li>
                        <a href='<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>'  title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'>
                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                       
						<i class="fa fa-search-plus" aria-hidden="true"></i> </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
</div>


 <div class="more-views mobile">
        <h2><?php echo $this->__('More Views') ?></h2>
        <div class="container-slider">
            <ul class="slider <?php echo $carous;?>" >
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <li>
                    <a href='<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>' class='cloud-zoom-gallery' title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'
                    rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageX, $bigImageY);?>' ">
                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(97,149);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                    
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
            <?php echo "$tumbSliderControl"; ?>
        </div>
    </div>
<!--
   <div id="containerrrr">
  <div class="inner">original inner div</div>
 </div> 
-->
    
    
<!--
<script>
jQuery("#fa-search-plus").click(function ($) {
  jQuery("#ps-toolbar-close").append('<div class="module_holder"><div class="module_item"><br>sendSMS</div></div>');
});
</script>
-->
