
  <link rel="stylesheet" href="<?php echo $this->getSkinUrl('journal/css/main.css');?>">
<?php $posts = $this->getPosts(); ?>
<div>
    <div role="main">

      <ul class="tiles-wrap animated" id="wookmark1">
        <?php $posts->count() ?>
        <?php $_iterator = 0; ?>
        <?php foreach ($posts as $post): ?>
            <li>
            	<div class="pp-wrap"></div>
               <div class="postTitle">
                        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                </div>
                       
                    <?php echo $post->getPostContent(); ?>
                
            </li>
        <?php endforeach; ?>
    </ul>
  </div>
</div>



<!-- Include the plug-in -->
  <script src="<?php echo $this->getSkinUrl('journal/js/wookmark.js');?>"></script>

  <!-- Once the page is loaded, initalize the plug-in. -->
  <script type="text/javascript">
    window.onload = function () {
      var wookmark1 = new Wookmark('#wookmark1', {

      });
    };
  </script>
